### ISSUE TITLE
runc's CVE-2024-21626

### ISSUE THREAD

**Issue by eslerm** [docker-snap/docker-snap#163]
The version of runc in this snap is likely affected by CVE-2024-21626.

The parts section of this snapcraft.yaml contains:
```
  runc:
    plugin: make
    source: https://github.com/opencontainers/runc.git
    # from https://github.com/moby/moby/releases/tag/v24.0.5
    source-tag: v1.1.7
```

runc before v1.1.12 is affected by CVE-2024-21626.

See https://www.openwall.com/lists/oss-security/2024/01/31/6 Please note upstream's security-announce mailing list.
